version: '3.7'

services:
  web:
    image: sinpapeles/hsd:2.4.0@sha256:b6fe94e60a75e9cf3cf526c9f122e121d4a7fe5131116c13250e2d2a4dba9bb5
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - '$APP_HANDSHAKE_HSD_PORT:$APP_HANDSHAKE_HSD_PORT'
    volumes:
      - '${APP_DATA_DIR}/data:/data'

    networks:
      default:
        ipv4_address: $APP_HANDSHAKE_HSD_IP
